services:
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - envyron_pg:/var/lib/postgresql/data

volumes:
  envyron_pg:
